# Generated by Django 3.0.6 on 2022-09-08 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrudBdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('corte', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_tipocarne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CrudBdd.Tipo_Carne')),
            ],
        ),
    ]
