# Generated by Django 3.0.6 on 2022-09-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudBdd', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_tipocarne',
        ),
    ]
